[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agentic-system-core"
version = "0.0.1"
authors = [
  { name="Andrei Nicolae Besleaga" },
]
description = "Reference implementation for the Agentic Knowledge Web."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://agenticsystemcore.com"
"Bug Tracker" = "https://github.com/andreibesleaga/agentic-system-core/issues"

[project.scripts]
agsc = "agentic_system_core.cli:main"