'use strict';
// CONTEXT Distribution (Emission) — what every hosting profile shares.
//
// A hosting profile is a plugin of the `deployment-profile` kind (AGSC-00-24): it
// reads the emitted route set and the header and redirect sets, and it answers the
// host's own configuration files as data. It never changes a route or a served
// byte: the application layer that writes its answer refuses any file that would
// replace a route (see `application/hosting.js`).
//
// Each profile declares:
//   * the four members every plugin declares (`kind`, `name`, `agsc_spec_version`,
//     `plugin_api_version`), so that it passes the same capability check as a
//     plugin someone else wrote;
//   * `claim` — the words a conformance claim uses to name it, because AGSC-06-01
//     obliges a writer targeting another host to "state which deployment profile it
//     emitted in its conformance claim" (AGSC-09-01);
//   * `limits` — what the host cannot do, stated plainly, so that no claim is made
//     that the host cannot carry;
//   * `emit(input)` — `{site, server, findings}`: `site` files are placed in the
//     build directory beside the route set (as `_headers` is), `server` files are
//     configuration kept outside it.
//
// Pure: a profile is handed data and answers data.

/** The specification version and plugin-API version every built-in profile targets. */
const TARGET = Object.freeze({ agsc_spec_version: '1.0.0', plugin_api_version: '1.0.0' });

/**
 * One built-in profile, frozen.
 *
 * @param {{name:string, title:string, claim:string, limits:Array<string>,
 *   emit:(input:object)=>{site:Array, server:Array, findings:Array}, with?:object}} spec
 *   `with` holds the profile's own helpers, exported beside it for its tests.
 * @returns {object}
 */
function define(spec) {
  return Object.freeze({
    ...(spec.with || {}),
    ...TARGET,
    claim: spec.claim,
    emit: spec.emit,
    kind: 'deployment-profile',
    limits: Object.freeze([...spec.limits]),
    name: spec.name,
    title: spec.title,
  });
}

/** An answer with nothing to write. */
function nothing(findings) {
  return { findings: findings || [], server: [], site: [] };
}

/**
 * The sentence of the conformance statement, naming the deployment profile as
 * AGSC-06-01 requires. Every value is given by the caller: this function reads no
 * clock and runs no vector.
 *
 * @param {{implementation:string, version:string, specVersion:string, level:number,
 *   date:string, passed:number, total:number, profile:{name:string, claim:string}}} c
 * @returns {string}
 */
function claimSentence(c) {
  return `${c.implementation} ${c.version} conforms to AgenticSystemCore ${c.specVersion},`
    + ` Level ${c.level}. Verified against the published conformance vectors on ${c.date}:`
    + ` ${c.passed} of ${c.total} passed. Deployment profile: ${c.profile.name} — ${c.profile.claim}.`;
}

/** A generated-file banner in a host's comment syntax. */
function banner(profile, comment) {
  return `${comment} Generated by agsc-host for the ${profile} deployment profile — never hand-edited (AGSC-06-04).`;
}

module.exports = { TARGET, banner, claimSentence, define, nothing };
