'use strict';
// AGSC-06-17, AGSC-11-03, AGSC-11-04 and AGSC-11-05: the header sets, generated
// (AGSC-06-04), never hand-maintained.

const test = require('node:test');
const assert = require('node:assert');
const headers = require('../../src/distribution/headers.js');
const { WELLKNOWN_PATH, WELLKNOWN_ALIAS, PROFILE, MEDIA_TYPE } = require('../../src/distribution/discovery.js');

const setFor = (sets, route) => sets.filter((s) => s.route === route).flatMap((s) => s.headers);

test('every public artefact carries the CORS pair and no credentials header (AGSC-11-03)', () => {
  const sets = headers.headerSets();
  for (const route of headers.PUBLIC_ARTEFACTS) {
    const names = setFor(sets, route).map(([k]) => k);
    assert.ok(names.includes('Access-Control-Allow-Origin'), `${route} has no CORS origin`);
    assert.ok(names.includes('Access-Control-Expose-Headers'), `${route} exposes no headers`);
  }
  assert.ok(!headers.headersFile().includes('Access-Control-Allow-Credentials'),
    'credentials must never be allowed on a public artefact');
});

test('a restricted node applies the wildcard to the discovery document alone (AGSC-11-20)', () => {
  const sets = headers.headerSets({ visibility: 'restricted' });
  assert.deepStrictEqual(setFor(sets, WELLKNOWN_PATH).map(([k]) => k).filter((k) => k.startsWith('Access-Control')),
    ['Access-Control-Allow-Origin', 'Access-Control-Expose-Headers']);
  assert.deepStrictEqual(setFor(sets, '/llms.txt').filter(([k]) => k.startsWith('Access-Control')), []);
});

test('the profile rides on the media type and on a Link header (AGSC-06-07, AGSC-11-04)', () => {
  const set = setFor(headers.headerSets(), WELLKNOWN_PATH);
  assert.ok(set.some(([k, v]) => k === 'Content-Type' && v === `${MEDIA_TYPE}; profile="${PROFILE}"`));
  assert.ok(set.some(([k, v]) => k === 'Link' && v === `<${PROFILE}>; rel="profile"`));
});

test('the three no-cache routes, and nothing else, are no-cache (AGSC-11-05)', () => {
  const sets = headers.headerSets();
  const noCache = sets.filter((s) => s.headers.some(([k, v]) => k === 'Cache-Control' && v === 'no-cache'))
    .map((s) => s.route).sort();
  assert.deepStrictEqual(noCache, [...headers.NO_CACHE].sort());
  assert.ok(!headers.headersFile().includes('immutable'),
    'no 1.0 route is digest-named, so `immutable` is emitted nowhere (AGSC-11-05)');
});

test('`/` carries the describedby response header (AGSC-11-05, AGSC-06-25)', () => {
  assert.deepStrictEqual(setFor(headers.headerSets(), '/'),
    [['Link', `<${WELLKNOWN_PATH}>; rel="describedby"; type="${MEDIA_TYPE}"`]]);
});

test('/pages/*.md carries the GFM variant parameter (AGSC-06-17)', () => {
  assert.ok(headers.headersFile().includes('Content-Type: text/markdown; charset=utf-8; variant=GFM'));
});

test('the CSP is default-src none with script-src self (AGSC-06-05, AGSC-06-17)', () => {
  assert.ok(headers.SECURITY_POLICY.startsWith("default-src 'none'"));
  assert.ok(headers.SECURITY_POLICY.includes("script-src 'self'"));
});

test('the 0.0.x discovery alias is a 301, and a rename adds one entry (AGSC-06-04/06-17)', () => {
  const text = headers.redirectsFile([{ from: '/old/', to: '/concepts/new/' }]);
  assert.ok(text.includes(`${WELLKNOWN_ALIAS} ${WELLKNOWN_PATH} 301`));
  assert.ok(text.includes('/old/ /concepts/new/ 301'));
  assert.ok(text.startsWith('# Generated by agsc build'));
});

test('the ETag is the quoted lowercase-hex SHA-256 (AGSC-11-05)', () => {
  assert.strictEqual(headers.etag('abc'), '"abc"');
});

test('AGSC-06-01: only the board JSON exports are typed JSON; the HTML board page keeps its own type', () => {
  const sets = headers.headerSets();
  const typed = (route) => setFor(sets, route).filter(([k]) => k === 'Content-Type').map(([, v]) => v);
  assert.deepStrictEqual(typed('/boards/*.json'), ['application/json; charset=utf-8']);
  assert.deepStrictEqual(typed('/boards/*'), [], 'a `/boards/*` splat would also match `/boards/<cluster>/`');
  // A `_headers` splat matches greedily, so no Content-Type rule may cover the HTML page.
  const covers = (pattern, path) => new RegExp(`^${pattern.split('*').map((part) => part
    .replace(/[.+?^${}()|[\]\\]/gu, '\\$&')).join('.*')}$`, 'u').test(path);
  const html = '/boards/project-board/';
  for (const set of sets) {
    if (set.headers.some(([k]) => k === 'Content-Type') && covers(set.route, html)) {
      assert.fail(`${set.route} sets a Content-Type on the HTML board page ${html}`);
    }
  }
  assert.ok(covers('/boards/*.json', '/boards/project-board.json'));
});
