'use strict';
// tests/distribution/page-tools-shards.test.js —.
//
// AGSC-06-21: above 500 items a writer MUST shard the search index as
// `/search-<nn>.json` and `/search.json` becomes the manifest `{shards:[…],
// docs_total}`; `/chunks.jsonl` shards on the same trigger, and every index route
// carrying more than 500 entries is paginated as `/<route>/page-<n>/`.
//
// AGSC-09-16 asks for ONE tool contract over two transports, with "results identical
// to the local MCP server's for the same input and Bundle". Until this file, the page
// half read `index.docs` — which a MANIFEST does not carry — so above 500 items every
// page tool went silent: `search` answered `{hits: []}`, `ask` answered the fixed
// no-answer string, and `read` answered `AGSC-E301` for an item that exists, with no
// diagnostic of any kind, while the local server answered correctly.
//
// The Bundle is GENERATED here — 520 items, not 520 committed fixture files — built
// once, and the EMITTED scripts are then run in a fake-browser harness whose `fetch`
// serves the emitted bytes and refuses every foreign URL. Every tool is compared,
// call for call, with the local server's answer.
//
// Deterministic: a fixed clock, no network, no wall clock, no randomness.

const test = require('node:test');
const assert = require('node:assert');
const vm = require('node:vm');
const nodeFs = require('node:fs');
const os = require('node:os');
const path = require('node:path');

const { createFileSystem, readSchemas } = require('../../src/adapters/node-fs.js');
const { createClock } = require('../../src/adapters/node-clock.js');
const validate = require('../../src/knowledge/validate.js');
const { loadBundle } = require('../../src/application/bundle.js');
const site = require('../../src/distribution/site.js');
const search = require('../../src/distribution/search.js');
const mcpTools = require('../../src/distribution/mcp-tools.js');
const pageTools = require('../../src/distribution/page-tools.js');

const ROOT = path.resolve(__dirname, '..', '..');
/** 2026-01-01T00:00:00Z — the fixed instant every test in this repository uses. */
const EPOCH = '1767225600';
/** AGSC-06-21's trigger, plus twenty: two shards, the second one short. */
const ITEMS = 520;
/** A token planted in exactly two items, one in each shard. */
const CROSS_SHARD_TOKEN = 'quartzbridge';

const temporaries = [];
test.after(() => {
  for (const dir of temporaries) nodeFs.rmSync(dir, { force: true, recursive: true });
});

/** The name of item `n`, in the slug order the writer shards by. */
const slugOf = (n) => `item-${String(n).padStart(4, '0')}`;

/** A Bundle of `ITEMS` published concepts, written to a throw-away directory. */
function generatedBundle() {
  const dir = nodeFs.mkdtempSync(path.join(os.tmpdir(), 'agsc-shards-'));
  temporaries.push(dir);
  nodeFs.mkdirSync(path.join(dir, 'content', 'concepts'), { recursive: true });
  nodeFs.mkdirSync(path.join(dir, '.well-known'), { recursive: true });
  nodeFs.writeFileSync(path.join(dir, '.well-known', 'security.txt'),
    'Contact: https://example.org/security-contact\n');
  nodeFs.writeFileSync(path.join(dir, 'agsc.config.json'), `${JSON.stringify({
    build: { out: 'www' },
    bundle: {
      id: 'sharded',
      license_prose: 'LicenseRef-AgenticSystemCore-Content-Use-1.0',
      license_schema: 'CC0-1.0',
      operator: 'human:tester',
    },
    site: { base: 'https://sharded.example/', tagline: 'Above the shard bound.', title: 'Sharded Bundle' },
    spec_version: '1.0.0-rc.5',
  }, null, 2)}\n`);
  nodeFs.writeFileSync(path.join(dir, 'content', 'index.md'), [
    '---',
    'spec_version: 1.0.0-rc.5',
    'title: Sharded Bundle',
    'description: A generated Bundle of five hundred and twenty items, used to exercise the AGSC-06-21 shard bound.',
    'base: https://sharded.example/',
    'lang: en',
    'license: LicenseRef-AgenticSystemCore-Content-Use-1.0',
    'prov:',
    '  origin: human',
    '  operator: human:tester',
    '---',
    '',
    '# Sharded Bundle',
    '',
    'Generated by the test that proves the page tools follow the index manifest.',
    '',
  ].join('\n'));
  for (let n = 0; n < ITEMS; n += 1) {
    const slug = slugOf(n);
    // The planted token sits in the FIRST shard (item 0001) and in the SECOND
    // (item 0501), so one query must reach across the shard boundary.
    const planted = (n === 1 || n === 501) ? ` ${CROSS_SHARD_TOKEN}` : '';
    // Every tenth item shares the word `beacon`, so a query has many hits to order.
    const shared = n % 10 === 0 ? ' beacon' : '';
    const body = [
      '',
      '## Intent',
      '',
      `Generated concept number ${n}.${planted}${shared}`,
      '',
      '## Notes',
      '',
      `The slug of this item is ${slug} and it carries no Link.`,
      '',
    ].join('\n');
    nodeFs.writeFileSync(path.join(dir, 'content', 'concepts', `${slug}.md`), [
      '---',
      'type: concept',
      `title: Item ${String(n).padStart(4, '0')}`,
      `description: A generated concept, number ${n} of the run, written to cross the five-hundred-item bound.`,
      'kind: explainer',
      'prov:',
      '  origin: human',
      '  operator: human:tester',
      '---',
      body,
    ].join('\n'));
  }
  return dir;
}

function built(dir) {
  const fs = createFileSystem(dir);
  const bundle = loadBundle(fs, { schemas: validate.schemas(readSchemas(ROOT)) });
  const clock = createClock({ env: { SOURCE_DATE_EPOCH: EPOCH } });
  return { bundle, ...site.build(bundle, { clock, fs }, { specVersion: '1.0.0-rc.5', version: '0.0.2' }) };
}

/**
 * The emitted scripts, run as a browser runs them: a fake `document.modelContext`,
 * a `fetch` that serves the EMITTED bytes for a same-origin path and REFUSES every
 * absolute or foreign URL, and no storage of any kind.
 *
 * @returns {Promise<{tools:object, fetched:string[], refused:string[], registered:number}>}
 */
async function browser(files, config) {
  const fetched = [];
  const refused = [];
  const registered = [];
  const context = vm.createContext({
    TextEncoder,
    console: { error() {}, log() {}, warn() {} },
  });
  context.document = { modelContext: { registerTool(tool) { registered.push(tool.name); } } };
  context.fetch = (route) => {
    const at = String(route);
    if (!at.startsWith('/') || at.startsWith('//')) {
      refused.push(at);
      return Promise.reject(new Error(`refused: ${at}`));
    }
    fetched.push(at);
    const bytes = files.get(at);
    return Promise.resolve(bytes === undefined
      ? { ok: false, text: () => Promise.resolve('') }
      : { ok: true, text: () => Promise.resolve(String(bytes)) });
  };
  context.globalThis = context;
  vm.runInContext(String(files.get('/compose/agsc-core.js')), context, { filename: 'agsc-core.js' });
  vm.runInContext(String(files.get('/compose/agsc-page-tools.js')), context, { filename: 'agsc-page-tools.js' });
  vm.runInContext(String(files.get('/compose/webmcp.js')), context, { filename: 'webmcp.js' });
  const api = vm.runInContext('globalThis.AGSC_PAGE_TOOLS', context);
  assert.strictEqual(api.BUNDLE_ID, (config.bundle || {}).id);
  assert.ok(api.ready !== null, 'the page did not start loading its corpus');
  await api.ready;
  return {
    fetched,
    refused,
    registered,
    tools: vm.runInContext('globalThis.AGSC_TOOLS', context),
    webmcp: vm.runInContext('globalThis.AGSC_WEBMCP', context),
  };
}

// --------------------------------------------------------------- the writer

test('AGSC-06-21: above 500 items /search.json IS the manifest and the shards carry the docs', () => {
  const { files } = built(generatedBundle());
  const manifest = JSON.parse(String(files.get('/search.json')));
  assert.deepStrictEqual(Object.keys(manifest).sort(), ['docs_total', 'shards']);
  assert.strictEqual(manifest.docs_total, ITEMS);
  assert.deepStrictEqual(manifest.shards, ['/search-01.json', '/search-02.json']);
  let docs = 0;
  for (const route of manifest.shards) {
    const shard = JSON.parse(String(files.get(route)));
    assert.ok(Array.isArray(shard.docs) && shard.docs.length > 0, `${route} carries no docs`);
    assert.ok(shard.docs.length <= search.ITEMS_PER_SHARD, `${route} is above the 500-item shard bound`);
    assert.ok(Buffer.byteLength(String(files.get(route)), 'utf8') <= 1000000,
      `${route} is above the 1 MB index budget of AGSC-06-21`);
    docs += shard.docs.length;
  }
  assert.strictEqual(docs, ITEMS);
  // The other size-triggered shapes: the chunk export and the paginated index routes.
  const chunks = JSON.parse(String(files.get('/chunks.jsonl')));
  // AGSC-06-31 as amended at rc.6: the shard manifest carries the content
  // version of AGSC-04-25 beside its two members, and JCS sorts it first.
  assert.deepStrictEqual(Object.keys(chunks).sort(), ['bundle_version', 'lines_total', 'shards']);
  assert.match(chunks.bundle_version, /^[A-Za-z0-9][A-Za-z0-9._+-]{0,63}$/u);
  assert.deepStrictEqual(chunks.shards, ['/chunks-01.jsonl', '/chunks-02.jsonl']);
  assert.ok(files.has('/concepts/page-2/index.html'), 'the /concepts/ index route was not paginated');
  // The front page lists no items (it links the index pages), so it is never paginated.
  assert.ok(!files.has('/page-2/index.html'), 'the front page was paginated');
  // And every item still has its own page, which is what the page tools read.
  for (const n of [0, 1, 499, 500, 501, ITEMS - 1]) {
    assert.ok(files.has(`/pages/${slugOf(n)}.md`), `no /pages/${slugOf(n)}.md`);
  }
});

// ------------------------------------------------- the page tools, in a browser

test('AGSC-09-16: the EMITTED page tools follow the manifest and answer as the local server does', async () => {
  const { bundle, files } = built(generatedBundle());
  const page = await browser(files, bundle.config);
  const local = mcpTools.tools(bundle, {});

  // The seven tools registered, and the page read the manifest and BOTH shards.
  assert.strictEqual(page.registered.length, 7);
  assert.ok(page.fetched.includes('/search.json'));
  assert.ok(page.fetched.includes('/search-01.json'), 'the first shard was never fetched');
  assert.ok(page.fetched.includes('/search-02.json'), 'the second shard was never fetched');
  assert.strictEqual(page.refused.length, 0, `the page left this origin: ${page.refused.join(' ')}`);
  assert.strictEqual(page.fetched.filter((r) => r.startsWith('/pages/')).length, ITEMS,
    'the page did not fetch one source file per published item');

  const calls = [
    // The query whose hits SPAN the two shards.
    ['search', { query: CROSS_SHARD_TOKEN }],
    ['ask', { question: CROSS_SHARD_TOKEN }],
    // A query with many hits, ordered by score then slug across both shards.
    ['search', { query: 'beacon' }],
    ['search', { query: 'generated concept' }],
    ['search', { query: 'nothing at all matches this' }],
    ['ask', { question: 'beacon' }],
    ['ask', { question: 'zzqqxx' }],
    // Items in the first shard, on the boundary, and in the second.
    ['read', { slug: slugOf(0) }],
    ['read', { slug: slugOf(1) }],
    ['read', { slug: slugOf(499) }],
    ['read', { slug: slugOf(500) }],
    ['read', { slug: slugOf(501) }],
    ['read', { slug: slugOf(ITEMS - 1) }],
    ['read', { slug: 'no-such-item' }],
    ['links', { slug: slugOf(500) }],
    ['links', { iri: `https://sharded.example/concepts/${slugOf(501)}/` }],
    ['propose', { slug: slugOf(501) }],
    ['compose', { selection: [slugOf(500)] }],
    ['remember', { body: 'x', kind: 'concept', operator: 'human:tester', title: 'A Remembered Note' }],
  ];
  for (const [name, args] of calls) {
    const expected = JSON.parse(JSON.stringify(local.call(name, args)));
    const answer = JSON.parse(JSON.stringify(await page.tools.call(name, args)));
    assert.deepStrictEqual(answer, expected,
      `${name}(${JSON.stringify(args)}) differs between the EMITTED page script and the local server`);
  }

  // The cross-shard query really does span the boundary, so the comparison above
  // proves what it claims.
  const hits = JSON.parse(JSON.stringify(
    (await page.tools.call('search', { query: CROSS_SHARD_TOKEN })).body.hits));
  assert.deepStrictEqual(hits.map((h) => h.slug), [slugOf(1), slugOf(501)]);
  assert.ok(hits.every((h) => h.score === 1));
});

test('AGSC-09-16: the module and the emitted script merge the shards identically', () => {
  const { bundle, files } = built(generatedBundle());
  const sources = {};
  for (const [route, text] of files) sources[route] = String(text);
  const corpus = pageTools.pageCorpus(sources, { bundleId: 'sharded' });
  assert.strictEqual(corpus.items.length, ITEMS);
  assert.strictEqual(corpus.index.docs.length, ITEMS);
  // The merged posting lists ARE the index the writer would have emitted unsharded.
  const whole = search.index(bundle.items.map((i) => ({
    body: i.body, ...i.frontmatter, slug: i.slug,
  })));
  assert.deepStrictEqual(corpus.index.docs, whole.docs);
  for (const token of Object.keys(whole.terms)) {
    assert.deepStrictEqual(corpus.index.terms[token], whole.terms[token],
      `the merged postings for ${JSON.stringify(token)} are not the unsharded ones`);
  }
});

test('a manifest whose shard is not served answers with a finding, never a silent empty result', async () => {
  const { bundle, files } = built(generatedBundle());
  const broken = new Map(files);
  broken.delete('/search-02.json');
  const page = await browser(broken, bundle.config);
  for (const [name, args] of [['search', { query: 'beacon' }], ['ask', { question: 'beacon' }]]) {
    const answer = await page.tools.call(name, args);
    assert.strictEqual(answer.type, 'error', `${name} answered silently over an incomplete index`);
    assert.strictEqual(answer.body.code, 'AGSC-E901');
    assert.match(answer.body.message, /search-02\.json/u);
  }
  // A manifest naming a route outside the AGSC-06-21 shape is not followed at all.
  const hostile = new Map(files);
  hostile.set('/search.json', JSON.stringify({
    docs_total: 2, shards: ['https://evil.example/search-01.json', '/../secret.json'],
  }));
  const guarded = await browser(hostile, bundle.config);
  assert.strictEqual(guarded.refused.length, 0, guarded.refused.join(' '));
  assert.ok(!guarded.fetched.some((r) => r.includes('evil.example') || r.includes('secret')),
    `the page followed a route a manifest named: ${guarded.fetched.join(' ')}`);
  const answer = await guarded.tools.call('search', { query: 'beacon' });
  assert.strictEqual(answer.type, 'error');
  assert.strictEqual(answer.body.code, 'AGSC-E901');
});

// ------------------------------------------- the index reader, on its own

test('AGSC-06-21: pageShardRoutes admits only /search-<nn>.json of this origin', () => {
  assert.deepStrictEqual(pageTools.pageShardRoutes(null), []);
  assert.deepStrictEqual(pageTools.pageShardRoutes({}), []);
  assert.deepStrictEqual(pageTools.pageShardRoutes({ shards: '/search-01.json' }), []);
  assert.deepStrictEqual(
    pageTools.pageShardRoutes({ shards: ['/search-01.json', '/search-01.json', '/search-02.json'] }),
    ['/search-01.json', '/search-02.json'], 'a repeated route must be followed once');
  assert.deepStrictEqual(pageTools.pageShardRoutes({
    shards: ['https://evil.example/search-01.json', '//evil.example/search-02.json',
      '/../secret.json', '/search.json', '/search-1.json', 'search-01.json'],
  }), [], 'a route outside the AGSC-06-21 shape must never be followed');
});

test('AGSC-06-21: pageIndexOf reads both shapes and says when it could not read them all', () => {
  assert.strictEqual(pageTools.pageIndexOf({}), null, 'no /search.json is no index');
  assert.strictEqual(pageTools.pageIndexOf({ '/search.json': 'not json' }), null);
  assert.strictEqual(pageTools.pageIndexOf({ '/search.json': '"a string"' }), null);
  // At or below the bound the document IS the index and is returned unchanged.
  const whole = { docs: [{ slug: 'a', title: 'A' }], terms: { alpha: [0] } };
  assert.deepStrictEqual(pageTools.pageIndexOf({ '/search.json': JSON.stringify(whole) }), whole);
  // Above it, the shard postings are offset by the running document count.
  const merged = pageTools.pageIndexOf({
    '/search.json': JSON.stringify({ docs_total: 3, shards: ['/search-01.json', '/search-02.json'] }),
    '/search-01.json': JSON.stringify({ docs: [{ slug: 'a' }, { slug: 'b' }], terms: { x: [0, 1], y: [1] } }),
    '/search-02.json': JSON.stringify({ docs: [{ slug: 'c' }], terms: { x: [0], z: [0] } }),
  });
  assert.deepStrictEqual(merged.docs.map((d) => d.slug), ['a', 'b', 'c']);
  assert.deepStrictEqual({ ...merged.terms }, { x: [0, 1, 2], y: [1], z: [2] });
  assert.strictEqual(merged.incomplete, undefined);
  // A shard that is not served, one that is not an index, and a count that disagrees.
  for (const [label, sources] of [
    ['a shard that was not served', {
      '/search.json': JSON.stringify({ docs_total: 3, shards: ['/search-01.json', '/search-02.json'] }),
      '/search-01.json': JSON.stringify({ docs: [{ slug: 'a' }], terms: {} }),
    }],
    ['a shard that is not an index', {
      '/search.json': JSON.stringify({ docs_total: 1, shards: ['/search-01.json'] }),
      '/search-01.json': JSON.stringify({ nonsense: true }),
    }],
    ['a manifest naming a route outside the shape', {
      '/search.json': JSON.stringify({ docs_total: 1, shards: ['https://evil.example/x.json'] }),
    }],
    ['a document count that disagrees with docs_total', {
      '/search.json': JSON.stringify({ docs_total: 9, shards: ['/search-01.json'] }),
      '/search-01.json': JSON.stringify({ docs: [{ slug: 'a' }], terms: {} }),
    }],
  ]) {
    const index = pageTools.pageIndexOf(sources);
    assert.strictEqual(index.incomplete, true, label);
    assert.ok(Array.isArray(index.missing) && index.missing.length > 0, label);
  }
  // A posting list that is not an array is skipped rather than trusted.
  const odd = pageTools.pageIndexOf({
    '/search.json': JSON.stringify({ docs_total: 1, shards: ['/search-01.json'] }),
    '/search-01.json': JSON.stringify({ docs: [{ slug: 'a' }], terms: { x: 'not an array' } }),
  });
  assert.deepStrictEqual({ ...odd.terms }, {});
  assert.strictEqual(odd.incomplete, undefined);
});
