'use strict';
/**
 * CONTEXT Distribution (Emission) — Surface: the `/compose/` page.
 *
 * Implements AGSC-06-01's `/compose/` route, AGSC-07-01 ("It MUST NOT require a
 * network, a key or a server"), AGSC-07-13 (the combiner in the page is the CLI's
 * own algebra — `composition/browser.js` emits its source text), and the **per-file
 * download** plus a "Download all (.zip)" link from `composition/archive.js`,
 * AGSC-07-24 (`/compose/?from=<slug>` shows the same composition a saved
 * architecture names) and AGSC-09-16 (the WebMCP tool registration,
 * feature-detected, through `distribution/webmcp.js`).
 *
 * Three files are emitted beside the page, because AGSC-06-17's own policy —
 * `default-src 'none'; script-src 'self'; style-src 'self'` — admits no inline
 * script and no inline style: `agsc-core.js` (the algebra), `agsc-compose.js` (this
 * module's controller) and `webmcp.js` (the registration). They are same-origin
 * assets of one route, never routes of their own; the reading of AGSC-06-01's
 * "exactly this route set" that would forbid a page's own script is recorded as a
 * specification item rather than resolved here.
 *
 * The page reads only routes AGSC-06-01 already fixes: `/graph.jsonld` for the items
 * (AGSC-05-16 read backwards, `composition/browser.js#itemsFromGraph`),
 * `/search.json` for the cluster and tag facets, and `/pages/<slug>.md`
 * (AGSC-06-02) for the body of a selected Procedure. No third-party origin, no
 * cookie, no `localStorage`, no beacon (AGSC-06-05).
 *
 * Pure function of its input.
 */

const { manifest } = require('./mcp-tools.js');

/** The four same-origin assets of the `/compose/` route, in load order. */
const ASSETS = Object.freeze(['agsc-core.js', 'agsc-page-tools.js', 'agsc-compose.js', 'webmcp.js']);

/**
 * AGSC-09-16: the scripts an ITEM page loads, in load order — the algebra (which
 * `compose` runs), the seven page tools, and the registration. They are the very
 * files the `/compose/` route serves, referenced absolutely, so one copy is fetched
 * once and cached for the whole node and no page inlines a byte of them
 * (AGSC-06-17's `script-src 'self'`, AGSC-06-21's page budget).
 *
 * The `/compose/` CONTROLLER is deliberately absent: it paints the compose form, and
 * an item page has none.
 */
const PAGE_TOOL_SCRIPTS = Object.freeze([
  '/compose/agsc-core.js', '/compose/agsc-page-tools.js', '/compose/webmcp.js',
]);

/** The seven tool names of AGSC-09-13, from the one manifest that defines them. */
function toolNames() {
  return manifest().tools.map((t) => t.name);
}

/**
 * The page controller. It is emitted as a classic script (AGSC-06-17's
 * `script-src 'self'`), and it:
 *   1. fetches `/graph.jsonld` and `/search.json` — same origin, no key;
 *   2. recovers the item records with the algebra's own `itemsFromGraph`;
 *   3. runs `compose()` on every change and renders the verdict, the closure
 *      explanations and the conflicts;
 *   4. emits the seven Harness files with `emit()` and offers ONE DOWNLOAD PER
 *      FILE and one "Download all (.zip)" link over the same files;
 *   5. installs `globalThis.AGSC_TOOLS` so that the WebMCP registration of
 *      AGSC-09-16 dispatches to the same implementation the stdio server uses for
 *      `compose`, and returns the AGSC-09-13a error envelope, with a registered
 *      code, for the six tools whose page implementation is not built yet.
 *
 * @param {object} [options]
 * @param {string} [options.specVersion]
 * @param {string} [options.licenseProse]
 * @returns {string}
 */
function controller(options) {
  const opts = options || {};
  const terms = 'LicenseRef-AgenticSystemCore-Content-Use-1.0';
  const license = opts.licenseProse === undefined ? terms : opts.licenseProse;
  return `'use strict';
// SPDX-License-Identifier: Apache-2.0 (the engine's code; the prose it carries keeps its own terms)
// AgenticSystemCore /compose/ controller (AGSC-07-01, AGSC-07-13, AGSC-09-16).
// GENERATED by src/distribution/compose-page.js — do not edit.
// No network beyond this origin, no key, no server, no cookie, no storage.
(function () {
  var CORE = globalThis.AGSC_CORE;
  var SPEC_VERSION = ${JSON.stringify(String(opts.specVersion === undefined ? '' : opts.specVersion))};
  var LICENSE_PROSE = ${JSON.stringify(license)};
  var state ={ base: '', bodies: {}, instant: '', items: [], selection: [], verdict: null, version: '' };
  globalThis.AGSC_COMPOSE = state;

  function el(id) { return typeof document === 'undefined' ? null : document.getElementById(id); }
  function text(node, value) { if (node) node.textContent = value; }

  // AGSC-09-16: one tool contract, two transports. All SEVEN tools are implemented
  // by \`agsc-page-tools.js\`, which this page loads before this controller and which
  // installs \`globalThis.AGSC_TOOLS\`. This controller therefore installs NOTHING on
  // that name: until rc.5 it installed a stub that answered \`compose\` and refused the
  // other six, and that stub — not the shared implementation — is what the site
  // actually shipped.

  /** The selection a \`/compose/?from=<slug>\` link names (AGSC-07-24). */
  function selectionFromQuery() {
    if (typeof location === 'undefined' || !location.search) return null;
    var match = /[?&]from=([^&]*)/.exec(location.search);
    return match === null ? decodeURIComponent('') || null : decodeURIComponent(match[1]);
  }

  function sha256Hex(value) {
    // Web Crypto, on this origin, over bytes this page already holds. It is the
    // ONLY asynchronous step, and the emitter stays synchronous and pure.
    var bytes = new TextEncoder().encode(value);
    return crypto.subtle.digest('SHA-256', bytes).then(function (buffer) {
      var out = '';
      var view = new Uint8Array(buffer);
      for (var i = 0; i < view.length; i += 1) out += view[i].toString(16).padStart(2, '0');
      return out;
    });
  }

  function render() {
    var result = CORE.compose(state.items, state.selection);
    state.verdict = result;
    var verdict = el('verdict');
    if (verdict) verdict.textContent = CORE.canonicalJson(CORE.verdictOf(result));
    var why = el('explanations');
    if (why) {
      why.textContent = '';
      why.hidden = result.added.length === 0;
      if (el('explanations-heading')) el('explanations-heading').hidden = why.hidden;
      for (var i = 0; i < result.added.length; i += 1) {
        var entry = result.added[i];
        var li = document.createElement('li');
        li.textContent = entry.slug + ' was added: ' + entry.path.map(function (step) {
          return step[0] + ' ' + step[1] + ' ' + step[2];
        }).join(', then ');
        why.appendChild(li);
      }
    }
    var problems = el('conflicts');
    if (problems) {
      problems.textContent = '';
      problems.hidden = result.conflicts.length === 0;
      if (el('conflicts-heading')) el('conflicts-heading').hidden = problems.hidden;
      for (var c = 0; c < result.conflicts.length; c += 1) {
        var conflict = result.conflicts[c];
        var row = document.createElement('li');
        row.textContent = conflict.code + ' on ' + conflict.key + ': ' + conflict.pair.join(' / ');
        problems.appendChild(row);
      }
    }
    text(el('validity'), result.valid ? 'valid' : 'invalid — no Harness is emitted (AGSC-07-17)');
    var button = el('download');
    if (button) button.disabled = !result.valid;
  }

  /**
   * AGSC-06-02 + AGSC-05-07: the body of a selected Procedure, for its SKILL.md.
   * \`/pages/<slug>.md\` is the lint-normalized SOURCE FILE, so the frontmatter block
   * is stripped before the bytes reach the Harness emitter — AGSC-07-13 makes the
   * page's Harness byte-identical to the CLI's, and the CLI emits the body.
   */
  function loadBodies(slugs) {
    var wanted = [];
    for (var i = 0; i < slugs.length; i += 1) {
      if (state.bodies[slugs[i]] === undefined) wanted.push(slugs[i]);
    }
    return Promise.all(wanted.map(function (slug) {
      return fetch('/pages/' + encodeURIComponent(slug) + '.md')
        .then(function (r) { return r.ok ? r.text() : ''; })
        .catch(function () { return ''; })
        .then(function (text) { state.bodies[slug] = bodyOf(text); });
    }));
  }

  /** The body half of a published source file (AGSC-02-01's closed guard). */
  function bodyOf(text) {
    var tools = globalThis.AGSC_PAGE_TOOLS;
    if (tools && typeof tools.pageSplitFrontmatter === 'function') {
      return tools.pageSplitFrontmatter(text).body;
    }
    return String(text === undefined || text === null ? '' : text);
  }
  state.bodyOf = bodyOf;

  function itemsWithBodies() {
    return state.items.map(function (item) {
      var copy = {};
      for (var key in item) if (Object.prototype.hasOwnProperty.call(item, key)) copy[key] = item[key];
      if (state.bodies[item.slug] !== undefined) copy.body = state.bodies[item.slug];
      return copy;
    });
  }

  /** Per-file download. One link per Harness file, no archive writer. */
  function emitHarness() {
    var result = state.verdict || CORE.compose(state.items, state.selection);
    if (!result.valid) return Promise.resolve(null);
    var procedures = result.selection.filter(function (slug) {
      for (var i = 0; i < state.items.length; i += 1) {
        if (state.items[i].slug === slug) return state.items[i].type === 'procedure';
      }
      return false;
    });
    return loadBodies(procedures).then(function () {
      return sha256Hex(CORE.selectionDigestInput(result));
    }).then(function (digest) {
      // AGSC-07-13: the name reaches the emitted bytes, so BOTH hosts derive it
      // from the selection digest with the algebra's own \`harnessName\` — the CLI
      // writes the same files into \`dist/harness/<name>/\` (AGSC-07-12).
      // AGSC-04-25: the content version is the one the discovery document states,
      // the one the CLI derives from the same history (AGSC-07-13).
      var out = CORE.emit(result, {
        base: state.base, bundleVersion: state.version === '' ? undefined : state.version,
        instant: state.instant, items: itemsWithBodies(),
        licenseProse: LICENSE_PROSE, name: CORE.harnessName(digest), selectionDigest: digest,
        specVersion: SPEC_VERSION
      });
      var list = el('files');
      if (list) {
        list.textContent = '';
        out.files.forEach(function (body, path) {
          var li = document.createElement('li');
          var link = document.createElement('a');
          link.href = URL.createObjectURL(new Blob([body], { type: 'text/plain;charset=utf-8' }));
          link.download = path.split('/').join('-');
          link.textContent = path;
          li.appendChild(link);
          list.appendChild(li);
        });
      }
      state.harness = out;
      return archiveLink(out, digest).then(function () { return out; });
    });
  }

  /**
   * "Download all (.zip)" beside the per-file links — the archive module the
   * CLI's \`compose --zip\` runs, over the same files and the same instant, so the
   * bytes cannot differ (AGSC-07-13); named with the content version, SHA-256 shown.
   */
  function archiveLink(out, digest) {
    var holder = el('archive');
    if (!holder || typeof CORE.archiveBytes !== 'function') return Promise.resolve(null);
    holder.textContent = '';
    var zip = CORE.archiveBytes(out.files, { instant: state.instant });
    if (zip.violations.length > 0) return Promise.resolve(null);
    state.archive = zip;
    var link = document.createElement('a');
    link.href = URL.createObjectURL(new Blob([zip.bytes], { type: 'application/zip' }));
    link.download = CORE.archiveName(CORE.harnessName(digest), state.version);
    link.textContent = 'Download all (.zip)';
    holder.appendChild(link);
    return crypto.subtle.digest('SHA-256', zip.bytes).then(function (buffer) {
      var hex = '';
      var view = new Uint8Array(buffer);
      for (var i = 0; i < view.length; i += 1) hex += view[i].toString(16).padStart(2, '0');
      var sum = document.createElement('span');
      sum.className = 'sha';
      sum.textContent = ' SHA-256 ' + hex;
      holder.appendChild(sum);
      return zip;
    });
  }

  function paint() {
    var list = el('items');
    if (!list) return;
    list.textContent = '';
    for (var i = 0; i < state.items.length; i += 1) {
      var item = state.items[i];
      if (item.type === 'cluster') continue;
      var li = document.createElement('li');
      var box = document.createElement('input');
      box.type = 'checkbox';
      box.value = item.slug;
      box.id = 'pick-' + item.slug;
      box.addEventListener('change', function (event) {
        var slug = event.target.value;
        var at = state.selection.indexOf(slug);
        if (event.target.checked && at === -1) state.selection.push(slug);
        if (!event.target.checked && at !== -1) state.selection.splice(at, 1);
        render();
      });
      var label = document.createElement('label');
      label.htmlFor = box.id;
      label.textContent = (item.title || item.slug) + ' (' + item.type + ')';
      li.appendChild(box);
      li.appendChild(label);
      list.appendChild(li);
    }
  }

  /**
   * AGSC-06-08: the build instant, from the discovery document's
   * \`agsc-generated-at\` on the \`describedby\` link. AGSC-07-13 makes the Harness
   * reproducible from "the graph plus the selection plus SOURCE_DATE_EPOCH", and this
   * is where a published node states that epoch — \`graph.jsonld\` does not carry it.
   * A document the page cannot read yields the empty string, never a wall clock
   * (AGSC-04-11): a page that guessed an instant would emit bytes the CLI cannot.
   */
  function describedValue(linkset, key) {
    var sets = (linkset && linkset.linkset) || [];
    for (var i = 0; i < sets.length; i += 1) {
      var described = (sets[i] && sets[i].describedby) || [];
      for (var j = 0; j < described.length; j += 1) {
        var values = described[j] && described[j][key];
        if (values && values.length > 0) return String(values[0]);
      }
    }
    return '';
  }
  function instantOf(linkset) { return describedValue(linkset, 'agsc-generated-at'); }
  state.instantOf = instantOf;

  /**
   * AGSC-06-08: the node's own base is the discovery document's \`anchor\` — the
   * \`site.base\` the CLI reads — never the origin the page happens to be served
   * from (a preview, a local server), which would put a different \`bundle:\` line
   * into the Harness than \`agsc compose\` writes (AGSC-07-13).
   */
  function baseOf(linkset) {
    var sets = (linkset && linkset.linkset) || [];
    var anchor = sets.length > 0 && sets[0] && typeof sets[0].anchor === 'string' ? sets[0].anchor : '';
    if (anchor === '') return location.origin + '/';
    return anchor.replace(/\\/+$/, '') + '/';
  }
  state.baseOf = baseOf;

  function start() {
    state.base = location.origin + '/';
    return fetch('/.well-known/knowledge-linkset').then(function (r) {
      return r.ok ? r.json() : null;
    }).catch(function () {
      return null;
    }).then(function (linkset) {
      state.base = baseOf(linkset);
      state.instant = instantOf(linkset);
      // The content version names the archive (AGSC-04-25); none → "unversioned".
      state.version = describedValue(linkset, 'agsc-bundle-version');
      return fetch('/graph.jsonld');
    }).then(function (r) { return r.json(); }).then(function (graph) {
      state.items = CORE.itemsFromGraph(graph);
      if (state.instant === '') state.instant = String(graph['dcterms:modified'] || '');
      paint();
      var from = selectionFromQuery();
      if (from !== null && from !== '') {
        // AGSC-07-24: the page shows the same composition the saved architecture
        // names. The selection block lives in the item's body, so the page reads
        // the item's Markdown view rather than guessing.
        return fetch('/pages/' + encodeURIComponent(from) + '.md')
          .then(function (r) { return r.ok ? r.text() : ''; })
          .then(function (body) {
            var fence = /\`\`\`yaml agsc-selection\\n([\\s\\S]*?)\`\`\`/.exec(body);
            if (fence === null) return;
            var picked = [];
            fence[1].split('\\n').forEach(function (line) {
              var m = /^\\s*-\\s+(\\S+)\\s*$/.exec(line);
              if (m !== null) picked.push(m[1]);
            });
            state.selection = picked;
            for (var i = 0; i < picked.length; i += 1) {
              var box = el('pick-' + picked[i]);
              if (box) box.checked = true;
            }
          });
      }
      return undefined;
    }).then(function () {
      render();
    }).catch(function (error) {
      text(el('validity'), 'the published graph could not be read: ' + error.message);
    });
  }

  state.emitHarness = emitHarness;
  state.render = render;
  state.start = start;
  if (typeof document !== 'undefined' && document.getElementById) {
    var button = el('download');
    if (button) button.addEventListener('click', function () { emitHarness(); });
    start();
  }
}());
`;
}

module.exports = { ASSETS, PAGE_TOOL_SCRIPTS, controller, toolNames };
