'use strict';
/**
 * CONTEXT Distribution (Emission) — Surface: the `/search/` page's one script.
 *
 * AGSC-06-01 makes `/search/` "the page whose data is `/search.json`". The page
 * itself (`html.js#searchPage`) is a form over that index with the item list beneath
 * it — the list is what a reader without script gets — and this module emits the
 * ONE same-origin classic script the page loads, `/search/agsc-search.js`, because
 * AGSC-06-17's `default-src 'none'; script-src 'self'` admits no inline script.
 *
 * The script searches with THE SAME TOKENIZER the index was built with (AGSC-06-23):
 * as `composition/browser.js` does for the combiner, it carries the OWN SOURCE TEXT
 * of `distribution/search.js#tokenize` and `#query` — `Function.prototype.toString()`
 * — so nothing is transcribed and the two hosts cannot drift. The manifest and its
 * shards (AGSC-06-21) are read by `page-tools.js#pageShardRoutes` and `#pageIndexOf`,
 * carried the same way: a page that cannot obtain every shard says so with
 * `AGSC-E901` and answers over nothing, as the rule requires.
 *
 * The script fetches `/search.json` and, above 500 items, the `/search-<nn>.json`
 * routes of this origin and nothing else (AGSC-06-05): no third-party origin, no
 * cookie, no storage, no beacon, no key. It renders every hit through DOM text
 * nodes, never through markup built from index text.
 *
 * Pure function of its input.
 */

const search = require('./search.js');
const pageTools = require('./page-tools.js');
const { TYPE_PLURAL } = require('../knowledge/chunks.js');

/** The one script of the `/search/` route. */
const SCRIPT_ROUTE = '/search/agsc-search.js';

/** The page's description: the Summary block and the `<meta name="description">`. */
const DESCRIPTION = 'Search every published item of this node; the index is /search.json and nothing leaves this origin.';

/** How many hits the page lists; the status line says when there are more. */
const SHOWN = 40;

/**
 * The route of a hit: `/<type-plural>/<slug>/` (AGSC-05-01). `search.json` carries no
 * type, so the writer hands the page the plural of every item that is NOT a concept
 * — the smallest table that resolves every published slug — and the page defaults
 * the rest to `/concepts/`.
 *
 * @param {Array<object>} items the published items.
 * @returns {Object<string,string>} slug -> plural, slugs in code-point order.
 */
function pluralsOf(items) {
  const out = {};
  const rows = [];
  for (const item of items) {
    const plural = TYPE_PLURAL[item.type] || TYPE_PLURAL.concept;
    if (plural !== TYPE_PLURAL.concept) rows.push([String(item.slug), plural]);
  }
  rows.sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));
  for (const [slug, plural] of rows) out[slug] = plural;
  return out;
}

/**
 * The script text.
 *
 * @param {object} [options]
 * @param {Object<string,string>} [options.plurals] from `pluralsOf`.
 * @param {string} [options.specVersion] recorded in the banner comment only.
 * @returns {string} a classic script, LF-terminated, ending in exactly one LF.
 */
function script(options) {
  const opts = options || {};
  const plurals = opts.plurals === undefined || opts.plurals === null ? {} : opts.plurals;
  const parts = ['\'use strict\';',
    '// SPDX-License-Identifier: Apache-2.0 (the engine\'s code; the prose it carries keeps its own terms)',
    '// AgenticSystemCore /search/ page (AGSC-06-01, AGSC-06-16, AGSC-06-21, AGSC-06-23).',
    '// GENERATED by src/distribution/search-page.js — do not edit. The tokenizer and the',
    '// ranking below are the SOURCE TEXT of the functions the writer ran to build the',
    '// index, so the page cannot search differently from how the index was built.',
    '// No network beyond this origin, no key, no server, no cookie, no storage.',
    `// spec_version: ${opts.specVersion === undefined ? 'unset' : opts.specVersion}`,
    '(function () {'];
  for (const name of search.PORTABLE) parts.push(String(search[name]));
  for (const name of ['pageShardRoutes', 'pageIndexOf']) parts.push(String(pageTools[name]));
  parts.push(`  var PLURALS = ${JSON.stringify(plurals)};
  var SHOWN = ${SHOWN};
  var API = { tokenize: tokenize, query: query, pageShardRoutes: pageShardRoutes, pageIndexOf: pageIndexOf, PLURALS: PLURALS };
  globalThis.AGSC_SEARCH = API;

  /** AGSC-05-01: the page of a hit, from the plural table the writer emitted. */
  API.routeOf = function (slug) {
    var plural = Object.prototype.hasOwnProperty.call(PLURALS, slug) ? PLURALS[slug] : 'concepts';
    return '/' + plural + '/' + encodeURIComponent(slug) + '/';
  };

  // AGSC-06-01: the routes the page reads — /search.json, and the /search-<nn>.json
  // shards it may name (AGSC-06-21) — all same-origin, and no URL read out of a document.
  var loaded = null;
  API.load = function (fetchLike) {
    if (loaded !== null) return loaded;
    var get = function (route) {
      return fetchLike(route).then(function (r) { return r.ok ? r.text() : null; })
        .catch(function () { return null; });
    };
    var sources = {};
    loaded = get('/search.json').then(function (text) {
      if (text === null) return null;
      sources['/search.json'] = text;
      var manifest = null;
      try { manifest = JSON.parse(text); } catch (e) { manifest = null; }
      return Promise.all(pageShardRoutes(manifest).map(function (route) {
        return get(route).then(function (shard) { if (shard !== null) sources[route] = shard; });
      })).then(function () { return pageIndexOf(sources); });
    });
    return loaded;
  };

  if (typeof document === 'undefined' || typeof fetch !== 'function') return;
  var form = document.getElementById('search-form');
  var input = document.getElementById('q');
  var results = document.getElementById('results');
  var status = document.getElementById('search-status');
  var fallback = document.getElementById('site-index');
  if (!form || !input || !results || !status) return;
  // Progressive: the form works only with this script, so only this script shows it.
  form.hidden = false;

  function say(text) { status.textContent = text; }
  function clear() { results.textContent = ''; }

  function paint(hits, q) {
    clear();
    var shown = hits.slice(0, SHOWN);
    for (var i = 0; i < shown.length; i += 1) {
      var li = document.createElement('li');
      var a = document.createElement('a');
      a.href = API.routeOf(shown[i].slug);
      a.textContent = shown[i].title;
      li.appendChild(a);
      if (shown[i].description) li.appendChild(document.createTextNode(': ' + shown[i].description));
      results.appendChild(li);
    }
    if (hits.length === 0) say('No results for \\u201c' + q + '\\u201d.');
    else say(hits.length + (hits.length === 1 ? ' result' : ' results') + (hits.length > SHOWN ? ', showing the first ' + SHOWN : ''));
  }

  API.run = function () {
    var q = String(input.value || '').trim();
    if (tokenize(q).length === 0) {
      clear();
      say('');
      if (fallback) fallback.hidden = false;
      return Promise.resolve([]);
    }
    return API.load(function (route) { return fetch(route, { credentials: 'omit' }); }).then(function (index) {
      if (index === null) {
        clear();
        if (fallback) fallback.hidden = false;
        say('The search index could not be loaded; the list below is still available.');
        return [];
      }
      if (index.incomplete === true) {
        // AGSC-06-21: a reader that cannot obtain every shard the manifest names
        // reports AGSC-E901 rather than answering over the part it holds.
        clear();
        if (fallback) fallback.hidden = false;
        say('AGSC-E901: the search index is incomplete (' + (index.missing || []).join(', ') + ' could not be read), so no answer is given; the list below is still available.');
        return [];
      }
      var hits = query(index, q);
      if (fallback) fallback.hidden = true;
      paint(hits, q);
      return hits;
    });
  };

  var timer = null;
  form.addEventListener('submit', function (event) { event.preventDefault(); API.pending = API.run(); });
  input.addEventListener('input', function () {
    clearTimeout(timer);
    timer = setTimeout(function () { API.pending = API.run(); }, 120);
  });
  // A link of the form /search/?q=<words> opens with the words already searched.
  var match = typeof location === 'undefined' ? null : /[?&]q=([^&]*)/.exec(location.search || '');
  if (match !== null) {
    try { input.value = decodeURIComponent(match[1].replace(/\\+/g, ' ')); } catch (e) { input.value = ''; }
    API.pending = API.run();
  }
  API.ready = API.pending === undefined ? Promise.resolve([]) : API.pending;
}());`);
  return `${parts.join('\n')}\n`;
}

module.exports = { DESCRIPTION, SCRIPT_ROUTE, SHOWN, pluralsOf, script };
